# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'flashy-view' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for flashy-view
	pod 'APParallaxHeader', '~> 0.1'
	pod 'SWTableViewCell', '~> 0.3.7'
end
